name: Pixeebot Fix Pull Request

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

permissions:
  id-token: write
  contents: read

jobs:
  pixeebot-fix:
    name: Pixeebot Fix Pull Request
    runs-on: ubuntu-latest
    timeout-minutes: 6

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Upload file and trigger analysis
        uses: pixee/upload-tool-results-action@91fff72fb865b0cbc020b9bc5588da2f3500ae50
        with:
            tool: 'contrast'
            contrast-api-url: ${{ vars.CONTRAST_API_URL }}
            contrast-org-id: ${{ vars.CONTRAST_ORG_ID }}
            contrast-app-id: ${{ vars.CONTRAST_APP_ID }}
            contrast-api-key: ${{ vars.CONTRAST_API_KEY }}
            contrast-token: ${{ vars.CONTRAST_TOKEN }}
            pixee-api-url: 'https://3yn27zgfgb.execute-api.us-east-1.amazonaws.com/prod'
